services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9999:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: ZNL%fkv0Ox9X
    command: start-dev
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: keycloak-db
    hostname: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ZNL%fkv0Ox9X
    volumes:
      - kc-data:/var/lib/postgresql/data
      - ./init-kc-db.sql:/docker-entrypoint-initdb.d/init-kc-db.sql
        
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"

volumes:
  kc-data:
    driver: local
    