CREATE DATABASE igapidb;
CREATE USER igapiuser WITH PASSWORD 'igapiuser';
GRANT CONNECT ON DATABASE igapidb TO igapiuser;
GRANT ALL PRIVILEGES ON DATABASE igapidb TO igapiuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO igapiuser;
GRANT CREATE ON SCHEMA public TO igapiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO igapiuser;
